[2025-01-06T10:12:06.904+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-06T10:12:06.943+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_dag.creating_schema_stg manual__2025-01-06T10:12:00.927727+00:00 [queued]>
[2025-01-06T10:12:06.963+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_dag.creating_schema_stg manual__2025-01-06T10:12:00.927727+00:00 [queued]>
[2025-01-06T10:12:06.964+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-06T10:12:06.995+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): creating_schema_stg> on 2025-01-06 10:12:00.927727+00:00
[2025-01-06T10:12:07.003+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=91) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-06T10:12:07.006+0000] {standard_task_runner.py:72} INFO - Started process 92 to run task
[2025-01-06T10:12:07.007+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kaggle_dag', 'creating_schema_stg', 'manual__2025-01-06T10:12:00.927727+00:00', '--job-id', '778', '--raw', '--subdir', 'DAGS_FOLDER/kaggle_dag.py', '--cfg-path', '/tmp/tmpgwv9l10d']
[2025-01-06T10:12:07.010+0000] {standard_task_runner.py:105} INFO - Job 778: Subtask creating_schema_stg
[2025-01-06T10:12:07.101+0000] {task_command.py:467} INFO - Running <TaskInstance: kaggle_dag.creating_schema_stg manual__2025-01-06T10:12:00.927727+00:00 [running]> on host 4f9b54363226
[2025-01-06T10:12:07.345+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_dag' AIRFLOW_CTX_TASK_ID='creating_schema_stg' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T10:12:00.927727+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-06T10:12:00.927727+00:00'
[2025-01-06T10:12:07.347+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-06T10:12:07.377+0000] {sql.py:278} INFO - Executing: CREATE SCHEMA IF NOT EXISTS stg;

TRUNCATE STG.adv;

CREATE TABLE IF NOT EXISTS STG.adv ( 
daily_time_spent_on_site float,
age SMALLINT,
area_income float,
daily_internet_usage float,
ad_topic_line VARCHAR,
city VARCHAR,
male SMALLINT,
country VARCHAR,
timestamp timestamp,
clicked_on_ad SMALLINT
);
[2025-01-06T10:12:07.396+0000] {base.py:84} INFO - Retrieving connection 'pg_connect'
[2025-01-06T10:12:07.412+0000] {base.py:84} INFO - Retrieving connection 'pg_connect'
[2025-01-06T10:12:07.420+0000] {sql.py:553} INFO - Running statement: CREATE SCHEMA IF NOT EXISTS stg;

TRUNCATE STG.adv;

CREATE TABLE IF NOT EXISTS STG.adv ( 
daily_time_spent_on_site float,
age SMALLINT,
area_income float,
daily_internet_usage float,
ad_topic_line VARCHAR,
city VARCHAR,
male SMALLINT,
country VARCHAR,
timestamp timestamp,
clicked_on_ad SMALLINT
);, parameters: None
[2025-01-06T10:12:07.427+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 498, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 558, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "stg.adv" does not exist

[2025-01-06T10:12:07.447+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=kaggle_dag, task_id=creating_schema_stg, run_id=manual__2025-01-06T10:12:00.927727+00:00, execution_date=20250106T101200, start_date=20250106T101206, end_date=20250106T101207
[2025-01-06T10:12:07.479+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-06T10:12:07.481+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 778 for task creating_schema_stg (relation "stg.adv" does not exist
; 92)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 498, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 558, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "stg.adv" does not exist

[2025-01-06T10:12:07.504+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-06T10:12:07.547+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-06T10:12:07.559+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
