[2025-01-06T17:10:49.316+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-06T17:10:49.351+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_dag.load_data manual__2025-01-06T17:10:33.683938+00:00 [queued]>
[2025-01-06T17:10:49.373+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_dag.load_data manual__2025-01-06T17:10:33.683938+00:00 [queued]>
[2025-01-06T17:10:49.375+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-06T17:10:49.418+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_data> on 2025-01-06 17:10:33.683938+00:00
[2025-01-06T17:10:49.431+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=313) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-06T17:10:49.435+0000] {standard_task_runner.py:72} INFO - Started process 314 to run task
[2025-01-06T17:10:49.443+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kaggle_dag', 'load_data', 'manual__2025-01-06T17:10:33.683938+00:00', '--job-id', '835', '--raw', '--subdir', 'DAGS_FOLDER/kaggle_dag.py', '--cfg-path', '/tmp/tmpazvm0yq2']
[2025-01-06T17:10:49.446+0000] {standard_task_runner.py:105} INFO - Job 835: Subtask load_data
[2025-01-06T17:10:49.558+0000] {task_command.py:467} INFO - Running <TaskInstance: kaggle_dag.load_data manual__2025-01-06T17:10:33.683938+00:00 [running]> on host 97bbb29a7501
[2025-01-06T17:10:49.903+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T17:10:33.683938+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-06T17:10:33.683938+00:00'
[2025-01-06T17:10:49.908+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-06T17:10:50.026+0000] {base.py:84} INFO - Retrieving connection 'pg_connect'
[2025-01-06T17:10:50.341+0000] {kaggle_dag.py:47} INFO - Данные вставились в БД
[2025-01-06T17:10:50.343+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-06T17:10:50.362+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-06T17:10:50.363+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=kaggle_dag, task_id=load_data, run_id=manual__2025-01-06T17:10:33.683938+00:00, execution_date=20250106T171033, start_date=20250106T171049, end_date=20250106T171050
[2025-01-06T17:10:50.419+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-06T17:10:50.474+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-06T17:10:50.480+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
